# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
      before_install:
        - pip install pep8==1.6.2
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes scrypt.py | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 tests scrypt.py
    - os: linux
      python: 2.7
      env:
        - WHEEL_NAME = scrypt-0.8.3-cp27-cp27mu-linux_x86_64.whl
        - USE_WHEEL=1
    - os: linux
      python: 3.5
      env:
        - WHEEL_NAME = crypt-0.8.3-cp35-cp35m-linux_x86_64.whl
        - USE_WHEEL=1
    - os: linux
      python: 3.6
    - os: linux
      python: 3.6
      env:
        - WHEEL_NAME = scrypt-0.8.3-cp36-cp36m-linux_x86_64.whl
        - USE_WHEEL=1
    - os: linux
      python: 3.6
      env:
        - USE_SDIST=1
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=2.7
        - WHEEL_NAME = scrypt-0.8.3-cp27-cp27m-macosx_10_6_intel.whl
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=3.5
        - WHEEL_NAME = scrypt-0.8.3-cp35-cp35m-macosx_10_6_intel.whl
    - os: osx
      osx_image: xcode9.2
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=3.6
        - WHEEL_NAME = scrypt-0.8.3-cp36-cp36m-macosx_10_6_intel.whl

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source util/travis_osx_install.sh; fi
  - ccache -s
  - which python; python --version
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --upgrade auditwheel; fi
  - mkdir ${TRAVIS_BUILD_DIR}/wheelhouse
  # Set numpy version first, other packages link against it
  #- pip install Cython matplotlib nose coverage codecov futures
  - set -o pipefail

script:
  # Define a fixed build dir so next step works
  - if [[ "${USE_WHEEL}" == "1" ]]; pip wheel . -v; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-listdeps ${WHEEL_NAME}; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-wheel -w fixed_wheels -v ${WHEEL_NAME}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then auditwheel show ${WHEEL_NAME}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then auditwheel repair ${WHEEL_NAME}; fi
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        #pip wheel . -v
        cp *.whl ${TRAVIS_BUILD_DIR}/wheelhouse/
        pip install scrypt*.whl -v
        python setup.py test
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local scrypt
        pushd dist
        pip install scrypt* -v
        popd
        python setup.py test
    else
        #CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        python setup.py build
        python setup.py test
    fi

deploy:
  provider: releases
  api-key: ${GITHUB_OAUTH}
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/wheelhouse/*
  skip_cleanup: true
  on:
    tags: false