# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
      before_install:
        - pip install pep8==1.6.2
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes scrypt.py | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 tests scrypt.py 
    - os: linux
      python: 3.6
      env:
        - USE_WHEEL=1
    - os: linux
      python: 3.6
      env:
        - USE_SDIST=1
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=3.5

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source util/travis_osx_install.sh; fi
  - ccache -s
  - which python; python --version
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  #- pip install Cython matplotlib nose coverage codecov futures
  - set -o pipefail
  - |

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        pip wheel . -v
        cp *.whl ${TRAVIS_BUILD_DIR}/wheelhouse/
        pip install scrypt*.whl -v
        python setup.py test
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local scrypt
        pushd dist
        pip install scrypt* -v
        python setup.py test
        popd
    else
        #CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        python setup.py build
        python setup.py test
    fi
deploy:
  provider: releases
  api-key: ${GITHUB_OAUTH}
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/wheelhouse/*
  skip_cleanup: true