[tool.cibuildwheel.linux]

# Install something required for the build
# (you might want to use build-system.requires instead)
before-all = "command -v yum > /dev/null && yum install -y openssl-devel"
before-all = "command -v apt-get > /dev/null && apt-get install -y libssl-dev"
